### ISSUE TITLE
Invented word

### ISSUE THREAD

**Issue by yagodlt** [ResponsiveImagesCG/ri-usecases#55]
Section '3.6 Matching media features and media types':
In the paragraph that commences with 'Allowing developers to reference images...' there is the word 'infeasible', which is not correct. The correct word is 'unfeasible'.

**Comment by nwtn** [comment]
The Economist has [a post about infeasible vs. unfeasible](http://www.economist.com/blogs/johnson/2012/07/variation). I have no real opinion on which we should use so, since both seem to be acceptable, I'm going to close this issue. If any of the other editors have a strong opinion on the matter, they're more than welcome to re-open and/or change the wording.

**Comment by marcoscaceres** [comment]
@yagodlt, thanks for the feedback. As we are not planning to republish this document, I'm inclined to leave it as is.

**Comment by yagodlt** [comment]
@marcoscaceres: that's fair enough.
@nwtn: thanks for the article, interesting reading! now I'm not so sure lol
